#!/bin/bash


target_bld=bld
rm $target_bld/*

cp MICM_prototype/* $target_bld
cp output_from_preprocessor/* $target_bld


cd $target_bld
#pgf95 -g -O -Mpreprocess precision.F90 chemistry_specification.F90 external_fields.F90 rate_constants.F90 forcing_and_jacobian.F90 solver_specification.F90 rosenbrock.dev.F90 ode_solve.F90 driver.F90

gfortran -g precision.F90 chemistry_specification.F90 external_fields.F90 rate_constants.F90 forcing_and_jacobian.F90 solver_specification.F90 rosenbrock.dev.F90 ode_solve.F90 driver.F90
mv -i a.out ../micm
