module factor_solve_utilities

  use musica_constants, only: r8 => musica_dk
  
  ! This code was generated by Preprocessor revision NA
  ! Preprocessor source NA
  
  ! This code is generated from tag undefined of the mechanism, undefined.  It is named undefined
  ! This tag was created on undefined by undefined and is marked as not buggy
  
    implicit none
  
    integer, parameter :: number_sparse_factor_elements = 23
  
    public :: factor, solve 
  
    contains
  
  
  subroutine backsolve_L_y_eq_b(LU,b,y)
  
  
    real(r8), intent(in) :: LU(:)
    real(r8), intent(in) :: b(:)
    real(r8), intent(out) :: y(:)
  
  
    y(1) = b(1)
    y(2) = b(2)
    y(3) = b(3)
    y(4) = b(4)
    y(5) = b(5)
    y(6) = b(6)
    y(6) = y(6) - LU(9) * y(5)
    y(7) = b(7)
    y(7) = y(7) - LU(2) * y(1)
    y(7) = y(7) - LU(10) * y(5)
    y(7) = y(7) - LU(12) * y(6)
    y(8) = b(8)
    y(8) = y(8) - LU(3) * y(1)
    y(8) = y(8) - LU(14) * y(7)
    y(9) = b(9)
    y(9) = y(9) - LU(4) * y(1)
    y(9) = y(9) - LU(15) * y(7)
    y(9) = y(9) - LU(19) * y(8)
  
  
  end subroutine backsolve_L_y_eq_b
  
  
  
  subroutine backsolve_U_x_eq_y(LU,y,x)
  
  
    real(r8), intent(in) :: LU(:)
    real(r8), intent(in) :: y(:)
    real(r8), intent(out) :: x(:)
    real(r8) :: temporary
  
  
    temporary = y(9)
    x(9) = LU(23) * temporary
    temporary = y(8)
    temporary = temporary - LU(22) * x(9)
    x(8) = LU(18) * temporary
    temporary = y(7)
    temporary = temporary - LU(17) * x(8)
    temporary = temporary - LU(21) * x(9)
    x(7) = LU(13) * temporary
    temporary = y(6)
    temporary = temporary - LU(16) * x(8)
    temporary = temporary - LU(20) * x(9)
    x(6) = LU(11) * temporary
    temporary = y(5)
    x(5) = LU(8) * temporary
    temporary = y(4)
    x(4) = LU(7) * temporary
    temporary = y(3)
    x(3) = LU(6) * temporary
    temporary = y(2)
    x(2) = LU(5) * temporary
    temporary = y(1)
    x(1) = LU(1) * temporary
  
  
  end subroutine backsolve_U_x_eq_y
  
  subroutine factor(LU)
  
  
    real(r8), intent(inout) :: LU(:)
  
  
    LU(1) = 1./LU(1)
    LU(2) = LU(2) * LU(1)
    LU(3) = LU(3) * LU(1)
    LU(4) = LU(4) * LU(1)
    LU(5) = 1./LU(5)
    LU(6) = 1./LU(6)
    LU(7) = 1./LU(7)
    LU(8) = 1./LU(8)
    LU(9) = LU(9) * LU(8)
    LU(10) = LU(10) * LU(8)
    LU(11) = 1./LU(11)
    LU(12) = LU(12) * LU(11)
    LU(17) = LU(17) - LU(12)*LU(16)
    LU(21) = LU(21) - LU(12)*LU(20)
    LU(13) = 1./LU(13)
    LU(14) = LU(14) * LU(13)
    LU(15) = LU(15) * LU(13)
    LU(18) = LU(18) - LU(14)*LU(17)
    LU(19) = LU(19) - LU(15)*LU(17)
    LU(22) = LU(22) - LU(14)*LU(21)
    LU(23) = LU(23) - LU(15)*LU(21)
    LU(18) = 1./LU(18)
    LU(19) = LU(19) * LU(18)
    LU(23) = LU(23) - LU(19)*LU(22)
    LU(23) = 1./LU(23)
  
  
  end subroutine factor
  
  subroutine solve(LU, x, b) 
  
    real(r8), intent(in) :: LU(:), b(:) ! solve LU * x = b 
    real(r8), intent(out) :: x(:) 
    real(r8) :: y(size(b)) 
  
    call backsolve_L_y_eq_b(LU, b, y)
    call backsolve_U_x_eq_y(LU, y, x)
  
  end subroutine solve 
  
  
  end module factor_solve_utilities