FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        cmake \
        gcc-c++ \
        gdb \
        git \
        ninja-build \
    && dnf clean all

# copy the MICM code
COPY . /micm/

# build the library and run the tests
RUN mkdir /build \
      && cd /build \
      && cmake \
        -G Ninja \
        -D CMAKE_BUILD_TYPE=release \
        -D MICM_ENABLE_CLANG_TIDY:BOOL=FALSE \
        -D MICM_ENABLE_KOKKOS=TRUE \
        ../micm \
      # -j 4 to prevent OOM on the Kokkos runner
      && ninja install -j 4

WORKDIR /build