FROM fedora:37

RUN dnf -y update \
    && dnf -y install \
        cmake \
        gcc-c++ \
        git \
        make \
        openmpi-devel \
    && dnf clean all

# copy the MICM code
COPY . /micm/

# build the library and run the tests
RUN mkdir /build \
      && cd /build \
      && cmake  \
        -D MICM_ENABLE_CLANG_TIDY:BOOL=FALSE \
        -D MICM_ENABLE_OPENMP:BOOL=TRUE \
        -D MICM_ENABLE_JSON:BOOL=TRUE \
        ../micm \
      && make install -j 8

WORKDIR /build