FROM fedora:latest

RUN dnf -y update \
    && dnf -y install \
        doxygen \
        gcc-c++ \
        gcc \
        git \
        cmake \
        make \
        python3 \
        python3-pip \
    && dnf clean all

COPY . /micm/

RUN pip3 install -r /micm/docs/requirements.txt

RUN mkdir /build \
      && cd /build \
      && cmake -D MICM_BUILD_DOCS=ON \
               /micm \
      && make docs

WORKDIR /build