# ignore all
*

# include things to copy
!CMakeLists.txt
# packaging/CMakeLists.txt installs these, so they must be in the build context
!LICENSE
!NOTICE
!src/
!docs/
!libs/
!test/
!etc/
!examples/
!cmake/
!packaging
!include/
!examples
!.clang-tidy
