# define RXTTAGCNT   542
# define ENTHALPYCNT    18
# define HETCNT   229
# define EXTCNT    14
# define CLSINDPRD    11
# define CLSINDPRD1     9
# define CLSINDPRD2     0
# define CLSINDPRD3     0
# define CLSINDPRD4     2
# define CLSINDPRD5     0
# define IMP_NZCNT  2285
# define ROD_NZCNT     0
# define IMP_LINCNT   392
# define ROD_LINCNT     0
# define IMP_NLNCNT   375
# define ROD_NLNCNT     0
# define RADJFLAG
# define PHTCNT   123
# define PHTCNTP1   124
# define RXNCNT   542
# define GASCNT   419
# define SETRXNCNT   351
# define USRRXNCNT    68
# define TDEPCNT   247
# define NCOL     2
# define NFS     3
# define NSLVD    41
# define VECLEN    32
# define INDEXM     1
# define INDEXH2O     0
# define PCNST   229
# define PCNSTP2   231
# define RELCNT     0
# define GRPCNT     0
# define CLSCNT1     2
# define CLSCNT2     0
# define CLSCNT3     0
# define CLSCNT4   227
# define CLSCNT5     0
# define EBIITERMAX     5
# define HOVITERMAX     7
# define IMPITERMAX     4
# define IMPJACITER     2
# define TROP_CHEM
