module rate_constants_utility 

use ccpp_kinds, only: r8 => kind_phys 

use rate_constant_functions 

use environmental_state_mod 

! This code was generated by Preprocessor revision fef2e1dcec7cb1bb7c703ed3c38345944d23c74d
! Preprocessor source http://github.com/NCAR/MechanismToCode

! This code is generated from tag 272 of the mechanism, Chapman.  It is named Chapman with MICM_j
! This tag was created on 2020-02-25 14:07:46.204967-07 by ajc and is marked as not buggy

  implicit none

  public :: p_rate_mapping,  k_rate_constant 

  contains

subroutine p_rate_mapping(tuv_rates, j_rate_const)
    real(KIND=r8),           intent(in)  :: tuv_rates(:) ! /sec 
    real(KIND=r8),           intent(out) :: j_rate_const(:) ! /sec 
    j_rate_const(1) = tuv_rates(1) 
    j_rate_const(2) = tuv_rates(2) 
    j_rate_const(3) = tuv_rates(3) 
end subroutine p_rate_mapping 

subroutine k_rate_constant(k_rate_constants, number_density_air, temperature, pressure, sad, aerosol_diameter, h2ovmr, o2vmr)
    real(KIND=r8),           intent(in)  :: temperature
    real(KIND=r8),           intent(in)  :: pressure
    real(KIND=r8),           intent(in)  :: sad(4)  ! aerosol surface area density 
    real(KIND=r8),           intent(in)  :: aerosol_diameter(4) ! aerosol diameter 
    real(KIND=r8),           intent(in)  :: number_density_air ! P/kT molecules/cm3 
    real(KIND=r8),           intent(in)  :: h2ovmr, o2vmr 
    real(KIND=r8),           intent(out) :: k_rate_constants(:) ! rate constant for the each reaction

    type( arrhenius_rate_param_type ) :: arrhenius_parameters 
    type( troe_rate_param_type ) :: troe_parameters 
    type( troe_low_pressure_rate_param_type ) :: troe_low_pressure_parameters 
    type( Troe_Reverse_rate_param_type ) :: Troe_Reverse_parameters 
    type( troe_chemical_activation_rate_param_type ) :: troe_chemical_activation_parameters 
    type( Simple_aerosol_heterogeneous_rate_rate_param_type ) :: Simple_aerosol_heterogeneous_rate_parameters 
    type( HET_glyoxyl_rate_param_type ) :: HET_glyoxyl_parameters 
    type( combined_CO_OH_rate_param_type ) :: combined_CO_OH_parameters 
    type( CH3COCH3_OH_rate_param_type ) :: CH3COCH3_OH_parameters 
    type( HO2_HO2_rate_param_type ) :: HO2_HO2_parameters 
    type( DMS_OH_rate_param_type ) :: DMS_OH_parameters 
    type( HNO3_OH_rate_param_type ) :: HNO3_OH_parameters 
    type( MCO3_NO2_rate_param_type ) :: MCO3_NO2_parameters 
    type( MPAN_M_rate_param_type ) :: MPAN_M_parameters 
    type( SO2_OH_rate_param_type ) :: SO2_OH_parameters 

    type(environmental_state_type) :: environmental_state 


    environmental_state%temperature = temperature 
    environmental_state%pressure = pressure 
    environmental_state%number_density_air = number_density_air 
    environmental_state%aerosol_surface_area_density(:) = sad(:) 
    environmental_state%aerosol_diameter(:) = aerosol_diameter(:) 

    environmental_state%h2ovmr = h2ovmr 

    environmental_state%o2_number_density = o2vmr*number_density_air 

    !N2_O1D_1
    !k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    Arrhenius_parameters%A = 2.150000e-11
    Arrhenius_parameters%C = -110.00
    Arrhenius_parameters%D = 300.0
    Arrhenius_parameters%B = 0.0
    Arrhenius_parameters%E = 0.0
    k_rate_constants(1) = Arrhenius(Arrhenius_parameters, environmental_state) 

    !O1D_O2_1
    !k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    Arrhenius_parameters%A = 3.300000e-11
    Arrhenius_parameters%C = -55.00
    Arrhenius_parameters%D = 300.0
    Arrhenius_parameters%B = 0.0
    Arrhenius_parameters%E = 0.0
    k_rate_constants(2) = Arrhenius(Arrhenius_parameters, environmental_state) 

    !O_O3_1
    !k_O_O3_1: O + O3 -> 2*O2
    Arrhenius_parameters%A = 8.000000e-12
    Arrhenius_parameters%C = 2060.00
    Arrhenius_parameters%D = 300.0
    Arrhenius_parameters%B = 0.0
    Arrhenius_parameters%E = 0.0
    k_rate_constants(3) = Arrhenius(Arrhenius_parameters, environmental_state) 

    !O_O2_M_1
    !k_O_O2_M_1: M, O + O2 -> 1*O3
    Troe_low_pressure_parameters%A_k0 = 6.0e-34
    Troe_low_pressure_parameters%B_k0 = 2.4
    Troe_low_pressure_parameters%C_k0 = 0.0
    k_rate_constants(4) = Troe_low_pressure(Troe_low_pressure_parameters, environmental_state) 

end subroutine k_rate_constant 


end module rate_constants_utility
