module factor_solve_utilities

use musica_constants, only: r8 => musica_dk

! This code was generated by Preprocessor revision NA
! Preprocessor source NA

! This code is generated from tag 272 of the mechanism, Chapman.  It is named Chapman with MICM_j
! This tag was created on 2020-02-25 14:07:46.204967-07 by ajc and is marked as not buggy

  implicit none

  integer, parameter :: number_sparse_factor_elements = 19

  public :: factor, solve 

  contains


subroutine backsolve_L_y_eq_b(LU,b,y)


  real(r8), intent(in) :: LU(:)
  real(r8), intent(in) :: b(:)
  real(r8), intent(out) :: y(:)


  y(1) = b(1)
  y(2) = b(2)
  y(3) = b(3)
  y(4) = b(4)
  y(5) = b(5)
  y(5) = y(5) - LU(5) * y(4)
  y(6) = b(6)
  y(6) = y(6) - LU(6) * y(4)
  y(6) = y(6) - LU(8) * y(5)
  y(7) = b(7)
  y(7) = y(7) - LU(10) * y(6)
  y(8) = b(8)
  y(8) = y(8) - LU(11) * y(6)
  y(8) = y(8) - LU(15) * y(7)


end subroutine backsolve_L_y_eq_b



subroutine backsolve_U_x_eq_y(LU,y,x)


  real(r8), intent(in) :: LU(:)
  real(r8), intent(in) :: y(:)
  real(r8), intent(out) :: x(:)
  real(r8) :: temporary


  temporary = y(8)
  x(8) = LU(19) * temporary
  temporary = y(7)
  temporary = temporary - LU(18) * x(8)
  x(7) = LU(14) * temporary
  temporary = y(6)
  temporary = temporary - LU(13) * x(7)
  temporary = temporary - LU(17) * x(8)
  x(6) = LU(9) * temporary
  temporary = y(5)
  temporary = temporary - LU(12) * x(7)
  temporary = temporary - LU(16) * x(8)
  x(5) = LU(7) * temporary
  temporary = y(4)
  x(4) = LU(4) * temporary
  temporary = y(3)
  x(3) = LU(3) * temporary
  temporary = y(2)
  x(2) = LU(2) * temporary
  temporary = y(1)
  x(1) = LU(1) * temporary


end subroutine backsolve_U_x_eq_y

subroutine factor(LU)


  real(r8), intent(inout) :: LU(:)


  LU(1) = 1./LU(1)
  LU(2) = 1./LU(2)
  LU(3) = 1./LU(3)
  LU(4) = 1./LU(4)
  LU(5) = LU(5) * LU(4)
  LU(6) = LU(6) * LU(4)
  LU(7) = 1./LU(7)
  LU(8) = LU(8) * LU(7)
  LU(13) = LU(13) - LU(8)*LU(12)
  LU(17) = LU(17) - LU(8)*LU(16)
  LU(9) = 1./LU(9)
  LU(10) = LU(10) * LU(9)
  LU(11) = LU(11) * LU(9)
  LU(14) = LU(14) - LU(10)*LU(13)
  LU(15) = LU(15) - LU(11)*LU(13)
  LU(18) = LU(18) - LU(10)*LU(17)
  LU(19) = LU(19) - LU(11)*LU(17)
  LU(14) = 1./LU(14)
  LU(15) = LU(15) * LU(14)
  LU(19) = LU(19) - LU(15)*LU(18)
  LU(19) = 1./LU(19)


end subroutine factor

subroutine solve(LU, x, b) 

  real(r8), intent(in) :: LU(:), b(:) ! solve LU * x = b 
  real(r8), intent(out) :: x(:) 
  real(r8) :: y(size(b)) 

  call backsolve_L_y_eq_b(LU, b, y)
  call backsolve_U_x_eq_y(LU, y, x)

end subroutine solve 


end module factor_solve_utilities
