module kinetics_utilities
use musica_constants, only: r8 => musica_dk

! This code was generated by Preprocessor revision NA
! Preprocessor source NA

! This code is generated from tag 272 of the mechanism, Chapman.  It is named Chapman with MICM_j
! This tag was created on 2020-02-25 14:07:46.204967-07 by ajc and is marked as not buggy

  use factor_solve_utilities, only:  factor

  implicit none

  private
  public :: dforce_dy_times_vector, factored_alpha_minus_jac, p_force, reaction_rates, reaction_names, &
            photolysis_names, dforce_dy, species_names

  ! Total number of reactions
  integer, parameter, public  :: number_of_reactions                = 7
  integer, parameter, public  :: number_of_photolysis_reactions     = 3
  integer, parameter, private :: photolysis_starting_reaction_index = 5
  integer, parameter, public  :: number_of_species                  = 8

  contains


subroutine dforce_dy(LU, rate_constant, number_density, number_density_air)

  ! Compute the derivative of the Forcing w.r.t. each chemical
  ! Also known as the Jacobian
  real(r8), intent(out) :: LU(:)
  real(r8), intent(in) :: rate_constant(:)
  real(r8), intent(in) :: number_density(:)
  real(r8), intent(in) :: number_density_air

  LU(:) = 0


  ! df_O/d(N2)
    !  k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    LU(6) = LU(6) + rate_constant(1) * number_density(5)


  ! df_O1D/d(N2)
    !  k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    LU(5) = LU(5) - rate_constant(1) * number_density(5)


  ! df_O/d(O)
    !  k_O_O3_1: O + O3 -> 2*O2
    LU(9) = LU(9) - rate_constant(3) * number_density(8)

    !  k_O_O2_M_1: M, O + O2 -> 1*O3
    LU(9) = LU(9) - rate_constant(4) * number_density(7) * number_density_air


  ! df_O2/d(O)
    !  k_O_O3_1: O + O3 -> 2*O2
    LU(10) = LU(10) + 2*rate_constant(3) * number_density(8)

    !  k_O_O2_M_1: M, O + O2 -> 1*O3
    LU(10) = LU(10) - rate_constant(4) * number_density(7) * number_density_air


  ! df_O3/d(O)
    !  k_O_O3_1: O + O3 -> 2*O2
    LU(11) = LU(11) - rate_constant(3) * number_density(8)

    !  k_O_O2_M_1: M, O + O2 -> 1*O3
    LU(11) = LU(11) + rate_constant(4) * number_density(7) * number_density_air


  ! df_O/d(O1D)
    !  k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    LU(8) = LU(8) + rate_constant(1) * number_density(4)

    !  k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    LU(8) = LU(8) + rate_constant(2) * number_density(7)


  ! df_O1D/d(O1D)
    !  k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    LU(7) = LU(7) - rate_constant(1) * number_density(4)

    !  k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    LU(7) = LU(7) - rate_constant(2) * number_density(7)


  ! df_O/d(O2)
    !  k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    LU(13) = LU(13) + rate_constant(2) * number_density(5)

    !  k_O_O2_M_1: M, O + O2 -> 1*O3
    LU(13) = LU(13) - rate_constant(4) * number_density(6) * number_density_air

    !  j_O2_1: O2 -> 2*O
    LU(13) = LU(13) + 2*rate_constant(5)


  ! df_O1D/d(O2)
    !  k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    LU(12) = LU(12) - rate_constant(2) * number_density(5)


  ! df_O2/d(O2)
    !  k_O_O2_M_1: M, O + O2 -> 1*O3
    LU(14) = LU(14) - rate_constant(4) * number_density(6) * number_density_air

    !  j_O2_1: O2 -> 2*O
    LU(14) = LU(14) - rate_constant(5)


  ! df_O3/d(O2)
    !  k_O_O2_M_1: M, O + O2 -> 1*O3
    LU(15) = LU(15) + rate_constant(4) * number_density(6) * number_density_air


  ! df_O/d(O3)
    !  k_O_O3_1: O + O3 -> 2*O2
    LU(17) = LU(17) - rate_constant(3) * number_density(6)

    !  j_O3_2: O3 -> 1*O + 1*O2
    LU(17) = LU(17) + rate_constant(7)


  ! df_O1D/d(O3)
    !  j_O3_1: O3 -> 1*O1D + 1*O2
    LU(16) = LU(16) + rate_constant(6)


  ! df_O2/d(O3)
    !  k_O_O3_1: O + O3 -> 2*O2
    LU(18) = LU(18) + 2*rate_constant(3) * number_density(6)

    !  j_O3_1: O3 -> 1*O1D + 1*O2
    LU(18) = LU(18) + rate_constant(6)

    !  j_O3_2: O3 -> 1*O + 1*O2
    LU(18) = LU(18) + rate_constant(7)


  ! df_O3/d(O3)
    !  k_O_O3_1: O + O3 -> 2*O2
    LU(19) = LU(19) - rate_constant(3) * number_density(6)

    !  j_O3_1: O3 -> 1*O1D + 1*O2
    LU(19) = LU(19) - rate_constant(6)

    !  j_O3_2: O3 -> 1*O + 1*O2
    LU(19) = LU(19) - rate_constant(7)

end subroutine dforce_dy

subroutine factored_alpha_minus_jac(LU, alpha, dforce_dy)
  !compute LU decomposition of [alpha * I - dforce_dy]

  real(r8), intent(in) :: dforce_dy(:)
  real(r8), intent(in) :: alpha
  real(r8), intent(out) :: LU(:)

  LU(:) = -dforce_dy(:)

! add alpha to diagonal elements

  LU(1) = -dforce_dy(1) + alpha 
  LU(2) = -dforce_dy(2) + alpha 
  LU(3) = -dforce_dy(3) + alpha 
  LU(4) = -dforce_dy(4) + alpha 
  LU(7) = -dforce_dy(7) + alpha 
  LU(9) = -dforce_dy(9) + alpha 
  LU(14) = -dforce_dy(14) + alpha 
  LU(19) = -dforce_dy(19) + alpha 

  call factor(LU) 

end subroutine factored_alpha_minus_jac

subroutine p_force(rate_constant, number_density, number_density_air, force)
  ! Compute force function for all molecules

  real(r8), intent(in) :: rate_constant(:)
  real(r8), intent(in) :: number_density(:)
  real(r8), intent(in) :: number_density_air
  real(r8), intent(out) :: force(:)



! Ar
  force(1) = 0


! CO2
  force(2) = 0


! H2O
  force(3) = 0


! N2
  force(4) = 0


! O1D
  force(5) = 0

  ! k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
  force(5) = force(5) - rate_constant(1) * number_density(4) * number_density(5)

  ! k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
  force(5) = force(5) - rate_constant(2) * number_density(5) * number_density(7)

  ! j_O3_1: O3 -> 1*O1D + 1*O2
  force(5) = force(5) + rate_constant(6) * number_density(8)


! O
  force(6) = 0

  ! k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
  force(6) = force(6) + rate_constant(1) * number_density(4) * number_density(5)

  ! k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
  force(6) = force(6) + rate_constant(2) * number_density(5) * number_density(7)

  ! k_O_O3_1: O + O3 -> 2*O2
  force(6) = force(6) - rate_constant(3) * number_density(6) * number_density(8)

  ! k_O_O2_M_1: M, O + O2 -> 1*O3
  force(6) = force(6) - rate_constant(4) * number_density(6) * number_density(7) * number_density_air

  ! j_O2_1: O2 -> 2*O
  force(6) = force(6) + 2*rate_constant(5) * number_density(7)

  ! j_O3_2: O3 -> 1*O + 1*O2
  force(6) = force(6) + rate_constant(7) * number_density(8)


! O2
  force(7) = 0

  ! k_O_O3_1: O + O3 -> 2*O2
  force(7) = force(7) + 2*rate_constant(3) * number_density(6) * number_density(8)

  ! k_O_O2_M_1: M, O + O2 -> 1*O3
  force(7) = force(7) - rate_constant(4) * number_density(6) * number_density(7) * number_density_air

  ! j_O2_1: O2 -> 2*O
  force(7) = force(7) - rate_constant(5) * number_density(7)

  ! j_O3_1: O3 -> 1*O1D + 1*O2
  force(7) = force(7) + rate_constant(6) * number_density(8)

  ! j_O3_2: O3 -> 1*O + 1*O2
  force(7) = force(7) + rate_constant(7) * number_density(8)


! O3
  force(8) = 0

  ! k_O_O3_1: O + O3 -> 2*O2
  force(8) = force(8) - rate_constant(3) * number_density(6) * number_density(8)

  ! k_O_O2_M_1: M, O + O2 -> 1*O3
  force(8) = force(8) + rate_constant(4) * number_density(6) * number_density(7) * number_density_air

  ! j_O3_1: O3 -> 1*O1D + 1*O2
  force(8) = force(8) - rate_constant(6) * number_density(8)

  ! j_O3_2: O3 -> 1*O + 1*O2
  force(8) = force(8) - rate_constant(7) * number_density(8)

end subroutine p_force

function reaction_rates(rate_constant, number_density, number_density_air)
  ! Compute reaction rates

  real(r8) :: reaction_rates(number_of_reactions)
  real(r8), intent(in) :: rate_constant(:)
  real(r8), intent(in) :: number_density(:)
  real(r8), intent(in) :: number_density_air

  ! k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
  reaction_rates(1) = rate_constant(1) * number_density(4) * number_density(5)

  ! k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
  reaction_rates(2) = rate_constant(2) * number_density(5) * number_density(7)

  ! k_O_O3_1: O + O3 -> 2*O2
  reaction_rates(3) = rate_constant(3) * number_density(6) * number_density(8)

  ! k_O_O2_M_1: M, O + O2 -> 1*O3
  reaction_rates(4) = rate_constant(4) * number_density(6) * number_density(7) * number_density_air

  ! j_O2_1: O2 -> 2*O
  reaction_rates(5) = rate_constant(5) * number_density(7)

  ! j_O3_1: O3 -> 1*O1D + 1*O2
  reaction_rates(6) = rate_constant(6) * number_density(8)

  ! j_O3_2: O3 -> 1*O + 1*O2
  reaction_rates(7) = rate_constant(7) * number_density(8)

end function reaction_rates


function reaction_names()
  ! Reaction names

  character(len=128) :: reaction_names(number_of_reactions)

  reaction_names(1) = 'N2_O1D_1'
  reaction_names(2) = 'O1D_O2_1'
  reaction_names(3) = 'O_O3_1'
  reaction_names(4) = 'O_O2_M_1'
  reaction_names(5) = 'O2_1'
  reaction_names(6) = 'O3_1'
  reaction_names(7) = 'O3_2'

end function reaction_names


function photolysis_names()
  ! Photolysis reaction names

  character(len=28) :: photolysis_names(number_of_photolysis_reactions)

  photolysis_names(1) = 'O2_1'
  photolysis_names(2) = 'O3_1'
  photolysis_names(3) = 'O3_2'

end function photolysis_names


function species_names()
  ! Chemical species names

  character(len=128) :: species_names(number_of_species)

  species_names(1) = 'Ar'
  species_names(2) = 'CO2'
  species_names(3) = 'H2O'
  species_names(4) = 'N2'
  species_names(5) = 'O1D'
  species_names(6) = 'O'
  species_names(7) = 'O2'
  species_names(8) = 'O3'

end function species_names


pure subroutine dforce_dy_times_vector(dforce_dy, vector, cummulative_product)

  !  Compute product of [ dforce_dy * vector ]
  !  Commonly used to compute time-truncation errors [dforce_dy * force ]

  real(r8), intent(in) :: dforce_dy(:) ! Jacobian of forcing
  real(r8), intent(in) :: vector(:)    ! Vector ordered as the order of number density in dy
  real(r8), intent(out) :: cummulative_product(:)  ! Product of jacobian with vector

  cummulative_product(:) = 0


  ! df_O/d(N2) * N2_temporary
  cummulative_product(6) = cummulative_product(6) + dforce_dy(6) * vector(4)


  ! df_O1D/d(N2) * N2_temporary
  cummulative_product(5) = cummulative_product(5) + dforce_dy(5) * vector(4)


  ! df_O/d(O) * O_temporary
  cummulative_product(6) = cummulative_product(6) + dforce_dy(9) * vector(6)


  ! df_O2/d(O) * O_temporary
  cummulative_product(7) = cummulative_product(7) + dforce_dy(10) * vector(6)


  ! df_O3/d(O) * O_temporary
  cummulative_product(8) = cummulative_product(8) + dforce_dy(11) * vector(6)


  ! df_O/d(O1D) * O1D_temporary
  cummulative_product(6) = cummulative_product(6) + dforce_dy(8) * vector(5)


  ! df_O1D/d(O1D) * O1D_temporary
  cummulative_product(5) = cummulative_product(5) + dforce_dy(7) * vector(5)


  ! df_O/d(O2) * O2_temporary
  cummulative_product(6) = cummulative_product(6) + dforce_dy(13) * vector(7)


  ! df_O1D/d(O2) * O2_temporary
  cummulative_product(5) = cummulative_product(5) + dforce_dy(12) * vector(7)


  ! df_O2/d(O2) * O2_temporary
  cummulative_product(7) = cummulative_product(7) + dforce_dy(14) * vector(7)


  ! df_O3/d(O2) * O2_temporary
  cummulative_product(8) = cummulative_product(8) + dforce_dy(15) * vector(7)


  ! df_O/d(O3) * O3_temporary
  cummulative_product(6) = cummulative_product(6) + dforce_dy(17) * vector(8)


  ! df_O1D/d(O3) * O3_temporary
  cummulative_product(5) = cummulative_product(5) + dforce_dy(16) * vector(8)


  ! df_O2/d(O3) * O3_temporary
  cummulative_product(7) = cummulative_product(7) + dforce_dy(18) * vector(8)


  ! df_O3/d(O3) * O3_temporary
  cummulative_product(8) = cummulative_product(8) + dforce_dy(19) * vector(8)


end subroutine dforce_dy_times_vector

end module kinetics_utilities
