module kinetics_utilities
use musica_constants, only: r8 => musica_dk
use constants, only : length, VLEN, STREAM0

! This code was generated by Preprocessor revision NA
! Preprocessor source NA

! This code is generated from tag undefined of the mechanism, undefined.  It is named undefined
! This tag was created on undefined by undefined and is marked as not buggy

  use factor_solve_utilities, only : factor, number_of_species, &
                                     number_sparse_factor_elements

  implicit none

  private
  public :: dforce_dy_times_vector, factored_alpha_minus_jac, p_force, calc_reaction_rates, reaction_names, &
            photolysis_names, dforce_dy, species_names

  ! Total number of reactions
  integer, parameter, public  :: number_of_reactions                = 7
  integer, parameter, public  :: number_of_photolysis_reactions     = 3

  contains


subroutine dforce_dy(LU, rate_constant, number_density, number_density_air)
  ! Compute the derivative of the Forcing w.r.t. each chemical
  ! Also known as the Jacobian
  real(r8), intent(out) :: LU(length,number_sparse_factor_elements)
  real(r8), intent(in) :: rate_constant(length,number_of_reactions)
  real(r8), intent(in) :: number_density(length,number_of_species)
  real(r8), intent(in) :: number_density_air(length,number_of_species)

  ! Local variables
  integer :: i, j 

  !$acc parallel default(present) vector_length(VLEN) async(STREAM0)
  !$acc loop gang vector collapse(2)
  do j = 1, number_sparse_factor_elements
     do i = 1, length
        LU(i,j) = 0
     end do
  end do
  !$acc end parallel

  !$acc parallel default(present) vector_length(VLEN) async(STREAM0)
  !$acc loop gang vector
  do i = 1, length
    ! df_O/d(M)
    !  k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    LU(i,2) = LU(i,2) - rate_constant(i,7) * number_density(i,7) * number_density(i,8)

    ! df_O2/d(M)
    !  k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    LU(i,3) = LU(i,3) - rate_constant(i,7) * number_density(i,7) * number_density(i,8)

    ! df_O3/d(M)
    !  k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    LU(i,4) = LU(i,4) + rate_constant(i,7) * number_density(i,7) * number_density(i,8)

    ! df_O1D/d(N2)
    !  k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    LU(i,9) = LU(i,9) - rate_constant(i,4) * number_density(i,6)

    ! df_O/d(N2)
    !  k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    LU(i,10) = LU(i,10) + rate_constant(i,4) * number_density(i,6)

    ! df_O1D/d(O1D)
    !  k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    LU(i,11) = LU(i,11) - rate_constant(i,4) * number_density(i,5)

    !  k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    LU(i,11) = LU(i,11) - rate_constant(i,5) * number_density(i,8)

    ! df_O/d(O1D)
    !  k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    LU(i,12) = LU(i,12) + rate_constant(i,4) * number_density(i,5)

    !  k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    LU(i,12) = LU(i,12) + rate_constant(i,5) * number_density(i,8)

    ! df_O/d(O)
    !  k_O_O3_1: O + O3 -> 2*O2
    LU(i,13) = LU(i,13) - rate_constant(i,6) * number_density(i,9)

    !  k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    LU(i,13) = LU(i,13) - rate_constant(i,7) * number_density(i,1) * number_density(i,8)

    ! df_O2/d(O)
    !  k_O_O3_1: O + O3 -> 2*O2
    LU(i,14) = LU(i,14) + 2*rate_constant(i,6) * number_density(i,9)

    !  k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    LU(i,14) = LU(i,14) - rate_constant(i,7) * number_density(i,1) * number_density(i,8)

    ! df_O3/d(O)
    !  k_O_O3_1: O + O3 -> 2*O2
    LU(i,15) = LU(i,15) - rate_constant(i,6) * number_density(i,9)

    !  k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    LU(i,15) = LU(i,15) + rate_constant(i,7) * number_density(i,1) * number_density(i,8)

    ! df_O1D/d(O2)
    !  k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    LU(i,16) = LU(i,16) - rate_constant(i,5) * number_density(i,6)

    ! df_O/d(O2)
    !  k_O2_1: O2 -> 2*O
    LU(i,17) = LU(i,17) + 2*rate_constant(i,1)

    !  k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    LU(i,17) = LU(i,17) + rate_constant(i,5) * number_density(i,6)

    !  k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    LU(i,17) = LU(i,17) - rate_constant(i,7) * number_density(i,1) * number_density(i,7)

    ! df_O2/d(O2)
    !  k_O2_1: O2 -> 2*O
    LU(i,18) = LU(i,18) - rate_constant(i,1)

    !  k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    LU(i,18) = LU(i,18) - rate_constant(i,7) * number_density(i,1) * number_density(i,7)

    ! df_O3/d(O2)
    !  k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    LU(i,19) = LU(i,19) + rate_constant(i,7) * number_density(i,1) * number_density(i,7)

    ! df_O1D/d(O3)
    !  k_O3_1: O3 -> 1*O1D + 1*O2
    LU(i,20) = LU(i,20) + rate_constant(i,2)

    ! df_O/d(O3)
    !  k_O3_2: O3 -> 1*O + 1*O2
    LU(i,21) = LU(i,21) + rate_constant(i,3)

    !  k_O_O3_1: O + O3 -> 2*O2
    LU(i,21) = LU(i,21) - rate_constant(i,6) * number_density(i,7)

    ! df_O2/d(O3)
    !  k_O3_1: O3 -> 1*O1D + 1*O2
    LU(i,22) = LU(i,22) + rate_constant(i,2)

    !  k_O3_2: O3 -> 1*O + 1*O2
    LU(i,22) = LU(i,22) + rate_constant(i,3)

    !  k_O_O3_1: O + O3 -> 2*O2
    LU(i,22) = LU(i,22) + 2*rate_constant(i,6) * number_density(i,7)

    ! df_O3/d(O3)
    !  k_O3_1: O3 -> 1*O1D + 1*O2
    LU(i,23) = LU(i,23) - rate_constant(i,2)

    !  k_O3_2: O3 -> 1*O + 1*O2
    LU(i,23) = LU(i,23) - rate_constant(i,3)

    !  k_O_O3_1: O + O3 -> 2*O2
    LU(i,23) = LU(i,23) - rate_constant(i,6) * number_density(i,7)

  end do
  !$acc end parallel

end subroutine dforce_dy

subroutine factored_alpha_minus_jac(LU, alpha, dforce_dy)
  ! Compute LU decomposition of [alpha * I - dforce_dy]

  real(r8), intent(in) :: dforce_dy(length,number_sparse_factor_elements)
  real(r8), intent(in) :: alpha
  real(r8), intent(out) :: LU(length,number_sparse_factor_elements)

  ! Local variables
  integer :: i, j

  !$acc parallel default(present) vector_length(VLEN) async(STREAM0)
  !$acc loop gang vector collapse(2)
  do j = 1, number_sparse_factor_elements 
     do i = 1, length
        LU(i,j) = -dforce_dy(i,j)
     end do
  end do
  !$acc end parallel

  ! add alpha to diagonal elements

  !$acc parallel default(present) vector_length(VLEN) async(STREAM0)
  !$acc loop gang vector
  do i = 1, length
    LU(i,1) = -dforce_dy(i,1) + alpha
    LU(i,5) = -dforce_dy(i,5) + alpha
    LU(i,6) = -dforce_dy(i,6) + alpha
    LU(i,7) = -dforce_dy(i,7) + alpha
    LU(i,8) = -dforce_dy(i,8) + alpha
    LU(i,11) = -dforce_dy(i,11) + alpha
    LU(i,13) = -dforce_dy(i,13) + alpha
    LU(i,18) = -dforce_dy(i,18) + alpha
    LU(i,23) = -dforce_dy(i,23) + alpha
  end do
  !$acc end parallel

  call factor(LU)

end subroutine factored_alpha_minus_jac

subroutine p_force(rate_constant, number_density, number_density_air, force)
  ! Compute force function for all molecules

  real(r8), intent(in) :: rate_constant(length,number_of_reactions)
  real(r8), intent(in) :: number_density(length,number_of_species)
  real(r8), intent(in) :: number_density_air(length)
  real(r8), intent(out) :: force(length,number_of_species)

  ! Local variables
  integer :: i

  !$acc parallel default(present) vector_length(VLEN) async(STREAM0)
  !$acc loop gang vector
  do i = 1, length

    ! M
    force(i,1) = 0

    ! Ar
    force(i,2) = 0

    ! CO2
    force(i,3) = 0

    ! H2O
    force(i,4) = 0

    ! N2
    force(i,5) = 0

    ! O1D
    force(i,6) = 0

    ! k_O3_1: O3 -> 1*O1D + 1*O2
    force(i,6) = force(i,6) + rate_constant(i,2) * number_density(i,9)

    ! k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    force(i,6) = force(i,6) - rate_constant(i,4) * number_density(i,5) * number_density(i,6)

    ! k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    force(i,6) = force(i,6) - rate_constant(i,5) * number_density(i,6) * number_density(i,8)

    ! O
    force(i,7) = 0

    ! k_O2_1: O2 -> 2*O
    force(i,7) = force(i,7) + 2*rate_constant(i,1) * number_density(i,8)

    ! k_O3_2: O3 -> 1*O + 1*O2
    force(i,7) = force(i,7) + rate_constant(i,3) * number_density(i,9)

    ! k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    force(i,7) = force(i,7) + rate_constant(i,4) * number_density(i,5) * number_density(i,6)

    ! k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    force(i,7) = force(i,7) + rate_constant(i,5) * number_density(i,6) * number_density(i,8)

    ! k_O_O3_1: O + O3 -> 2*O2
    force(i,7) = force(i,7) - rate_constant(i,6) * number_density(i,7) * number_density(i,9)

    ! k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    force(i,7) = force(i,7) - rate_constant(i,7) * number_density(i,1) * number_density(i,7) * number_density(i,8)

    ! O2
    force(i,8) = 0

    ! k_O2_1: O2 -> 2*O
    force(i,8) = force(i,8) - rate_constant(i,1) * number_density(i,8)

    ! k_O3_1: O3 -> 1*O1D + 1*O2
    force(i,8) = force(i,8) + rate_constant(i,2) * number_density(i,9)

    ! k_O3_2: O3 -> 1*O + 1*O2
    force(i,8) = force(i,8) + rate_constant(i,3) * number_density(i,9)

    ! k_O_O3_1: O + O3 -> 2*O2
    force(i,8) = force(i,8) + 2*rate_constant(i,6) * number_density(i,7) * number_density(i,9)

    ! k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    force(i,8) = force(i,8) - rate_constant(i,7) * number_density(i,1) * number_density(i,7) * number_density(i,8)

    ! O3
    force(i,9) = 0

    ! k_O3_1: O3 -> 1*O1D + 1*O2
    force(i,9) = force(i,9) - rate_constant(i,2) * number_density(i,9)

    ! k_O3_2: O3 -> 1*O + 1*O2
    force(i,9) = force(i,9) - rate_constant(i,3) * number_density(i,9)

    ! k_O_O3_1: O + O3 -> 2*O2
    force(i,9) = force(i,9) - rate_constant(i,6) * number_density(i,7) * number_density(i,9)

    ! k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    force(i,9) = force(i,9) + rate_constant(i,7) * number_density(i,1) * number_density(i,7) * number_density(i,8)
  end do
  !$acc end parallel

end subroutine p_force

subroutine calc_reaction_rates(rate_constant, number_density, number_density_air, reaction_rates)
  ! Compute reaction rates

  real(r8), intent(in)  :: rate_constant(length,number_of_reactions)
  real(r8), intent(in)  :: number_density(length,number_of_species)
  real(r8), intent(in)  :: number_density_air(length)
  real(r8), intent(out) :: reaction_rates(length,number_of_reactions)

  ! Local variables
  integer :: i

  !$acc parallel default(present) vector_length(VLEN)
  !$acc loop gang vector
  do i = 1, length

    ! k_O2_1: O2 -> 2*O
    reaction_rates(i,1) = rate_constant(i,1) * number_density(i,8)

    ! k_O3_1: O3 -> 1*O1D + 1*O2
    reaction_rates(i,2) = rate_constant(i,2) * number_density(i,9)

    ! k_O3_2: O3 -> 1*O + 1*O2
    reaction_rates(i,3) = rate_constant(i,3) * number_density(i,9)

    ! k_N2_O1D_1: N2 + O1D -> 1*O + 1*N2
    reaction_rates(i,4) = rate_constant(i,4) * number_density(i,5) * number_density(i,6)

    ! k_O1D_O2_1: O1D + O2 -> 1*O + 1*O2
    reaction_rates(i,5) = rate_constant(i,5) * number_density(i,6) * number_density(i,8)

    ! k_O_O3_1: O + O3 -> 2*O2
    reaction_rates(i,6) = rate_constant(i,6) * number_density(i,7) * number_density(i,9)

    ! k_M_O_O2_1: M + O + O2 -> 1*O3 + 1*M
    reaction_rates(i,7) = rate_constant(i,7) * number_density(i,1) * number_density(i,7) * number_density(i,8)

  end do
  !$acc end parallel

end subroutine calc_reaction_rates


function reaction_names()
  ! Reaction names

  character(len=128) :: reaction_names(number_of_reactions)

  reaction_names(1) = 'O2_1'
  reaction_names(2) = 'O3_1'
  reaction_names(3) = 'O3_2'
  reaction_names(4) = 'N2_O1D_1'
  reaction_names(5) = 'O1D_O2_1'
  reaction_names(6) = 'O_O3_1'
  reaction_names(7) = 'M_O_O2_1'

end function reaction_names


function photolysis_names()
  ! Photolysis reaction names

  character(len=28) :: photolysis_names(number_of_photolysis_reactions)

  photolysis_names(1) = 'O2_1'
  photolysis_names(2) = 'O3_1'
  photolysis_names(3) = 'O3_2'

end function photolysis_names


function species_names()
  ! Chemical species names

  character(len=128) :: species_names(number_of_species)

  species_names(1) = 'M'
  species_names(2) = 'Ar'
  species_names(3) = 'CO2'
  species_names(4) = 'H2O'
  species_names(5) = 'N2'
  species_names(6) = 'O1D'
  species_names(7) = 'O'
  species_names(8) = 'O2'
  species_names(9) = 'O3'

end function species_names


pure subroutine dforce_dy_times_vector(dforce_dy, vector, cummulative_product)
  !  Compute product of [ dforce_dy * vector ]
  !  Commonly used to compute time-truncation errors [dforce_dy * force ]

  real(r8), intent(in) :: dforce_dy(length,number_sparse_factor_elements) ! Jacobian of forcing
  real(r8), intent(in) :: vector(length,number_of_species)    ! Vector ordered as the order of number density in dy
  real(r8), intent(out) :: cummulative_product(length,number_of_species)  ! Product of jacobian with vector

  ! Local variables
  integer :: i, j

  !$acc parallel default(present) vector_length(VLEN)
  !$acc loop gang vector collapse(2)
  do j = 1, number_of_species
     do i = 1, length
        cummulative_product(i,j) = 0
     end do
  end do
  !$acc end parallel

  !$acc parallel default(present) vector_length(VLEN)
  !$acc loop gang vector
  do i = 1, length

    ! df_O/d(M) * M_temporary
    cummulative_product(i,7) = cummulative_product(i,7) + dforce_dy(i,2) * vector(i,1)

    ! df_O2/d(M) * M_temporary
    cummulative_product(i,8) = cummulative_product(i,8) + dforce_dy(i,3) * vector(i,1)

    ! df_O3/d(M) * M_temporary
    cummulative_product(i,9) = cummulative_product(i,9) + dforce_dy(i,4) * vector(i,1)

    ! df_O1D/d(N2) * N2_temporary
    cummulative_product(i,6) = cummulative_product(i,6) + dforce_dy(i,9) * vector(i,5)

    ! df_O/d(N2) * N2_temporary
    cummulative_product(i,7) = cummulative_product(i,7) + dforce_dy(i,10) * vector(i,5)

    ! df_O1D/d(O1D) * O1D_temporary
    cummulative_product(i,6) = cummulative_product(i,6) + dforce_dy(i,11) * vector(i,6)

    ! df_O/d(O1D) * O1D_temporary
    cummulative_product(i,7) = cummulative_product(i,7) + dforce_dy(i,12) * vector(i,6)

    ! df_O/d(O) * O_temporary
    cummulative_product(i,7) = cummulative_product(i,7) + dforce_dy(i,13) * vector(i,7)

    ! df_O2/d(O) * O_temporary
    cummulative_product(i,8) = cummulative_product(i,8) + dforce_dy(i,14) * vector(i,7)

    ! df_O3/d(O) * O_temporary
    cummulative_product(i,9) = cummulative_product(i,9) + dforce_dy(i,15) * vector(i,7)

    ! df_O1D/d(O2) * O2_temporary
    cummulative_product(i,6) = cummulative_product(i,6) + dforce_dy(i,16) * vector(i,8)

    ! df_O/d(O2) * O2_temporary
    cummulative_product(i,7) = cummulative_product(i,7) + dforce_dy(i,17) * vector(i,8)

    ! df_O2/d(O2) * O2_temporary
    cummulative_product(i,8) = cummulative_product(i,8) + dforce_dy(i,18) * vector(i,8)

    ! df_O3/d(O2) * O2_temporary
    cummulative_product(i,9) = cummulative_product(i,9) + dforce_dy(i,19) * vector(i,8)

    ! df_O1D/d(O3) * O3_temporary
    cummulative_product(i,6) = cummulative_product(i,6) + dforce_dy(i,20) * vector(i,9)

    ! df_O/d(O3) * O3_temporary
    cummulative_product(i,7) = cummulative_product(i,7) + dforce_dy(i,21) * vector(i,9)

    ! df_O2/d(O3) * O3_temporary
    cummulative_product(i,8) = cummulative_product(i,8) + dforce_dy(i,22) * vector(i,9)

    ! df_O3/d(O3) * O3_temporary
    cummulative_product(i,9) = cummulative_product(i,9) + dforce_dy(i,23) * vector(i,9)

  end do
  !$acc end parallel

end subroutine dforce_dy_times_vector

end module kinetics_utilities
