module factor_solve_utilities

use musica_constants, only: r8 => musica_dk

! This code was generated by Preprocessor revision NA
! Preprocessor source NA

! This is a stub of the preprocessor-generated module

  implicit none

  integer, parameter :: number_sparse_factor_elements = 0

  public :: factor, solve

  contains


subroutine backsolve_L_y_eq_b(LU,b,y)


  real(r8), intent(in) :: LU(:)
  real(r8), intent(in) :: b(:)
  real(r8), intent(out) :: y(:)


end subroutine backsolve_L_y_eq_b



subroutine backsolve_U_x_eq_y(LU,y,x)


  real(r8), intent(in) :: LU(:)
  real(r8), intent(in) :: y(:)
  real(r8), intent(out) :: x(:)
  real(r8) :: temporary


end subroutine backsolve_U_x_eq_y

subroutine factor(LU)


  real(r8), intent(inout) :: LU(:)


end subroutine factor

subroutine solve(LU, x, b)

  real(r8), intent(in) :: LU(:), b(:) ! solve LU * x = b
  real(r8), intent(out) :: x(:)
  real(r8) :: y(size(b))

  call backsolve_L_y_eq_b(LU, b, y)
  call backsolve_U_x_eq_y(LU, y, x)

end subroutine solve


end module factor_solve_utilities
