module kinetics_utilities
use musica_constants, only: r8 => musica_dk

! This code was generated by Preprocessor revision NA
! Preprocessor source NA

! This is a stub of the preprocessor generated module

  use factor_solve_utilities, only:  factor

  implicit none

  private
  public :: dforce_dy_times_vector, factored_alpha_minus_jac, p_force, reaction_rates, reaction_names, &
            photolysis_names, dforce_dy, species_names

  ! Total number of reactions
  integer, parameter, public  :: number_of_reactions                = 0
  integer, parameter, public  :: number_of_photolysis_reactions     = 0
  integer, parameter, private :: photolysis_starting_reaction_index = 0
  integer, parameter, public  :: number_of_species                  = 0

  contains


subroutine dforce_dy(LU, rate_constant, number_density, number_density_air)

  ! Compute the derivative of the Forcing w.r.t. each chemical
  ! Also known as the Jacobian
  real(r8), intent(out) :: LU(:)
  real(r8), intent(in) :: rate_constant(:)
  real(r8), intent(in) :: number_density(:)
  real(r8), intent(in) :: number_density_air

  LU(:) = 0


end subroutine dforce_dy

subroutine factored_alpha_minus_jac(LU, alpha, dforce_dy)
  !compute LU decomposition of [alpha * I - dforce_dy]

  real(r8), intent(in) :: dforce_dy(:)
  real(r8), intent(in) :: alpha
  real(r8), intent(out) :: LU(:)

  LU(:) = -dforce_dy(:)

  call factor(LU)

end subroutine factored_alpha_minus_jac

subroutine p_force(rate_constant, number_density, number_density_air, force)
  ! Compute force function for all molecules

  real(r8), intent(in) :: rate_constant(:)
  real(r8), intent(in) :: number_density(:)
  real(r8), intent(in) :: number_density_air
  real(r8), intent(out) :: force(:)


end subroutine p_force

function reaction_rates(rate_constant, number_density, number_density_air)
  ! Compute reaction rates

  real(r8) :: reaction_rates(number_of_reactions)
  real(r8), intent(in) :: rate_constant(:)
  real(r8), intent(in) :: number_density(:)
  real(r8), intent(in) :: number_density_air


end function reaction_rates


function reaction_names()
  ! Reaction names

  character(len=128) :: reaction_names(number_of_reactions)


end function reaction_names


function photolysis_names()
  ! Photolysis reaction names

  character(len=28) :: photolysis_names(number_of_photolysis_reactions)


end function photolysis_names


function species_names()
  ! Chemical species names

  character(len=128) :: species_names(number_of_species)


end function species_names


pure subroutine dforce_dy_times_vector(dforce_dy, vector, cummulative_product)

  !  Compute product of [ dforce_dy * vector ]
  !  Commonly used to compute time-truncation errors [dforce_dy * force ]

  real(r8), intent(in) :: dforce_dy(:) ! Jacobian of forcing
  real(r8), intent(in) :: vector(:)    ! Vector ordered as the order of number density in dy
  real(r8), intent(out) :: cummulative_product(:)  ! Product of jacobian with vector

  cummulative_product(:) = 0


end subroutine dforce_dy_times_vector

end module kinetics_utilities
