module rate_constants_utility

use musica_constants, only: r8 => musica_dk

use rate_constant_functions

use micm_environment, only : environment_t

! This code was generated by Preprocessor revision NA
! Preprocessor source NA

! This is a stub of the preprocessor generated code

  implicit none

  public :: set_photolysis_rate_constants, k_rate_constant

  contains

subroutine set_photolysis_rate_constants(rate_constants, photolysis_rate_constants)
    real(KIND=r8), intent(out) :: rate_constants(:) ! s-1
    real(KIND=r8), intent(in)  :: photolysis_rate_constants(:) ! s-1


end subroutine set_photolysis_rate_constants

subroutine k_rate_constant(k_rate_constants, environmental_state)
    real(KIND=r8),         intent(out) :: k_rate_constants(:) ! rate constant for the each reaction
    type(environment_t), intent(in)  :: environmental_state

    type( arrhenius_rate_param_type ) :: arrhenius_parameters
    type( troe_rate_param_type ) :: troe_parameters
    type( troe_low_pressure_rate_param_type ) :: troe_low_pressure_parameters
    type( Troe_Reverse_rate_param_type ) :: Troe_Reverse_parameters
    type( troe_chemical_activation_rate_param_type ) :: troe_chemical_activation_parameters
    type( Simple_aerosol_heterogeneous_rate_rate_param_type ) :: Simple_aerosol_heterogeneous_rate_parameters
    type( HET_glyoxyl_rate_param_type ) :: HET_glyoxyl_parameters
    type( combined_CO_OH_rate_param_type ) :: combined_CO_OH_parameters
    type( CH3COCH3_OH_rate_param_type ) :: CH3COCH3_OH_parameters
    type( HO2_HO2_rate_param_type ) :: HO2_HO2_parameters
    type( DMS_OH_rate_param_type ) :: DMS_OH_parameters
    type( HNO3_OH_rate_param_type ) :: HNO3_OH_parameters
    type( MCO3_NO2_rate_param_type ) :: MCO3_NO2_parameters
    type( MPAN_M_rate_param_type ) :: MPAN_M_parameters
    type( SO2_OH_rate_param_type ) :: SO2_OH_parameters


end subroutine k_rate_constant


end module rate_constants_utility
