module chemistry_specification

use precision, only: r8

!*****************************************************************************************
! This module is completely auto-generated by Configurator
!*****************************************************************************************

!----------------------------------------------------------------------------------------------
! This module contains information for the chemistry solver from the configuator
!----------------------------------------------------------------------------------------------

implicit none
private

public :: chemistry_init, nspecies_specified

  integer, parameter :: nSpecies_specified = 3  ! Number of chemical species for the run

contains 
  
  subroutine chemistry_init( absTol, relTol)

    real(r8), pointer, intent(inout) :: absTol(:)
    real(r8), pointer, intent(inout) :: relTol(:)

    absTol(:) = 1.e-9_r8
    relTol(:) = 1.e-4_r8

  end subroutine chemistry_init


end module chemistry_specification
