!> \file kinetics_module.F90
!!  Contains type definitions for MICM kinetics

module kinetics_module

!*****************************************************************************************
! This module is completely auto-generated by Configurator
!*****************************************************************************************

implicit none

private
public :: kinetics_type

integer, parameter :: r8 = selected_real_kind( 15 )

! rateConst are computed at the beginning of the 
!   chemistry_box_solver time step.
!   They are not computed for internal steps of the
!   box-model time-step advancer
! rateConst will be thread-safe memory provided elsewhere.
! rate_constant_store will be an accessor to memory
! For now, it is allocated here. It is not thread safe

! Filter with CPP for PGI compiler
!> \section arg_table_kinetics_type
!! | local_name   | standard_name                                 | long_name                               | units   | rank | type          |    kind   | intent | optional |
!! |--------------|-----------------------------------------------|-----------------------------------------|---------|------|---------------|-----------|--------|----------|
!! | theKinetics  | kinetics_data                                 | chemistry kinetics                      | DDT     |    0 | kinetics_type |           | none   | F        |
!! | nTotRxt      | num_chemical_reactions                        | total number of chemical reactions      | count   |    0 | integer       |           | none   | F        |
!!

type kinetics_type
  private
  integer :: nReact
  real(r8), allocatable :: rateConst(:)
contains
  private
  procedure, public :: rateConst_init 
  procedure, public :: rateConst_update
  procedure, public :: rateConst_print
  procedure, public :: force
  procedure, public :: jac
  final             :: DasEnder
end type kinetics_type

contains

  !------------------------------------------------------
  ! allocate rateConst member array
  !------------------------------------------------------
  subroutine rateConst_init( this, nRxt )
      
    class(kinetics_type) :: this
    integer, intent(in)  :: nRxt    ! total number of reactions

    this%nReact = nRxt
    if( .not. allocated(this%rateConst)) then
      allocate( this%rateConst(nRxt) )
    else
      write(*,*) 'rateConst_init: rateConst already allocated'
    endif

  end subroutine rateConst_init

  !------------------------------------------------------
  ! update rateConst
  ! Execute once for the chemistry-time-step advance
  ! Not called from the solver
  !------------------------------------------------------
  subroutine rateConst_update( this, k_rateConst, j_rateConst )

    class(kinetics_type) :: this
    real(r8), intent(in) :: k_rateConst(:) ! externally supplied rate constants
    real(r8), intent(in) :: j_rateConst(:)
    
    associate( rateConstants => this%rateConst )
      ! Rate Constants
#include "../../MICM_chemistry/generated/rateconstants.inc"
    end associate

  end subroutine rateConst_update

  subroutine rateConst_print( this )

    class(kinetics_type) :: this

    write(*,*) 'rate constants:'
    write(*,'(1p,5(1x,g0))') this%rateConst(:)

  end subroutine rateConst_print

  !---------------------------
  !  cleanup when k_rateConst type is removed
  !---------------------------
  subroutine DasEnder( this )

    type(kinetics_type) :: this

    if( allocated( this%rateConst ) ) then
       deallocate( this%rateConst )
    endif

  end subroutine DasEnder

  !---------------------------
  ! Compute time rate of change of each molecule (vmr) given reaction rates
  !---------------------------
  function force( this, vmr )

    class(kinetics_type) :: this
    real(r8), intent(in)::  vmr(:)              ! volume mixing ratios of each component in order
    real(r8)            ::  force(size(vmr))    ! rate of change of each molecule

    real(r8) :: rates(this%nReact)          ! rates of each reaction

    call compute_rates(this, vmr, rates)

#include "../../MICM_chemistry/generated/forcing.inc"

  end function force

  !---------------------------
  ! Compute sensitivity of molecular forcing to each vmr (derivative of force w.r.t. each vmr)
  !---------------------------
  function jac( this, vmr )

    class(kinetics_type) :: this
    real(r8), intent(in)::  vmr(:)         ! volume mixing ratios of each component in order
    real(r8) :: jac(size(vmr),size(vmr))   ! sensitivity of forcing to changes in each vmr

    ! Jacobian
    jac(:,:) = 0._r8

    associate( rateConstants => this%rateConst )
#include "../../MICM_chemistry/generated/jacobian.inc"
    end associate

  end function jac

  !---------------------------
  ! Compute reaction rates, given vmr of each species and rate constants
  !---------------------------
  subroutine compute_rates(this, vmr, rates )

    class(kinetics_type)  :: this
    real(r8), intent(in)  :: vmr(:)     ! volume mixing ratios of each component in order
    real(r8), intent(out) :: rates(:)   ! rates for each reaction (sometimes called velocity of reaction)

    associate( rateConstants => this%rateConst )
#include "../../MICM_chemistry/generated/rates.inc"
    end associate

  end subroutine compute_rates

end module kinetics_module
