module solver_specification

!*****************************************************************************************
! This module is completely auto-generated by Configurator
!*****************************************************************************************

implicit none
private

  integer, public, parameter :: ndiv = 30000
  
end module solver_specification
