name: Clang-Tidy

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tidy:
    name: Run Clang-Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan includes
        run: docker build --target scan-includes --progress=plain -f docker/Dockerfile.clang-tidy .

      - name: Scan CUDA source
        run: docker build --target scan-cuda-source --progress=plain -f docker/Dockerfile.clang-tidy .

      - name: Scan Test files
        run: docker build --target scan-tests --progress=plain -f docker/Dockerfile.clang-tidy .
