name: Designated Runner

on: 
  push:
  pull_request:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  job1:
    name: job1
    runs-on: gha-runner-micm
    steps:
      - uses: actions/checkout@v4

      - name: Install cmake
        run: |
          apt update
          apt install -y cmake

      - name: Run Cmake 
        run: cmake -S . -B build -DMICM_GPU_TYPE="a10"

      - name: Build
        run: cmake --build build --parallel 10

      - name: Run tests
        run: |
          cd build
          ctest --rerun-failed --output-on-failure . --verbose -j 10
