name: Designated Runner

on: 
  push:
  pull_request:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  job1:
    name: job1
    runs-on: gha-runner-micm
    steps:
      - name: test1
        run: ls
