name: Designated Runner

on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  job1:
    name: job1
    runs-on: gha-runner-micm
    container:
      image: nvcr.io/nvidia/nvhpc:23.7-devel-cuda12.2-ubuntu22.04
      options: --gpus all
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
           apt update
           apt install -y cmake g++

      - name: Run Cmake 
        run: cmake -S . -B build -DMICM_GPU_TYPE="a10"
      
      - name: Copy cublas headers
        run: |
          cp -r /opt/nvidia/hpc_sdk/*/23.7/cuda/include/* /usr/include/

      - name: Build
        run: cmake --build build --parallel 10

      - name: Run tests
        run: |
          cd build
          ctest --rerun-failed --output-on-failure . --verbose -j 10
