name: Ubuntu

on: 
  push:
    # branches:
    #   - main
  pull_request:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    continue-on-error: true
    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler: [{CC: gcc, CXX: g++}, {CC: clang, CXX: clang++}]
        ubuntu_version: [latest, 20.04, 22.04, 24.04]
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    env:
      CC: ${{ matrix.compiler.CC }}
      CXX: ${{ matrix.compiler.CXX }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cmake 
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build --parallel 10

      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build_type }} --rerun-failed --output-on-failure . --verbose -j 10